### ISSUE TITLE
Issue formating console output

### ISSUE THREAD

**Issue by RemyDeB** [gl-eb/generate-stickers-AveryL7871#11]
Hey, 
Your code works perfectly well. 
I'm facing a minor issue with console outputs :

![image](https://github.com/gl-eb/generate-stickers-AveryL7871/assets/116943597/d0d16385-98b3-459d-8a09-bed8612407d8)

I have try running on cmd and Windows powershell, it's the same issue with color and fond. 
 
Regards,
Remy

**Comment by gl-eb** [comment]
Thanks for the report! I'm glad to hear that the script also (mostly) works on Windows. Do you mind me asking what version of Windows you are on so I can mention this in the README?

**Comment by gl-eb** [comment]
I'll keep this issue open for now since #12 is more of a hacky fix for the problem than a sustainable solution (see https://stackoverflow.com/a/54955094)

I'm tempted to look into using [Colorama](https://github.com/tartley/colorama) for cross-platform colored command line output. The downside being that Colorama would be the first non-standard python library dependency.

**Comment by RemyDeB** [comment]
I use Windows 10 22H2 with python 3.11.6 and MiKTeX 23.10.12. 

Also notice this error at the end that don't afffect pdf output.
![image](https://github.com/gl-eb/generate-stickers-AveryL7871/assets/116943597/47444491-4792-4ff2-ad29-51337d62d626)

Regards

**Comment by gl-eb** [comment]
I've created a new issue for this error. Thanks for the report

Regarding colored command line output. Could you give the version of the script in the [11-formating-console-output](https://github.com/gl-eb/generate-stickers-AveryL7871/tree/11-formating-console-output) branch a try and let me know if the output is colored?
It has colorama as a new dependency, but should at least do all of the changes to the output automatically, depending on which OS the script is run on.

**Comment by RemyDeB** [comment]
I can confirm output is colored.

![image](https://github.com/gl-eb/generate-stickers-AveryL7871/assets/116943597/bf124449-75cb-486f-b606-87c70ed32ace)

Just an error, thinks you forgot to ```import os```.

**Comment by gl-eb** [comment]
Ah, my bad. Thank you! The `develop` branch should now include both the os import as well as use colorama for cross-platform text formatting
I'll merge into `main` and tag a new release in the next few days
